### ISSUE TITLE
Load TWBS js & css by default

### ISSUE THREAD

**Issue by redpik** [TheWebShop/bootstrap-shortcodes#39] opened 2014-07-10 08:06 UTC
I think TWBS js & css should be unchecked by default, because this plugin is used by themes with TWBS already loaded.

**Comment by infn8** [comment] 2015-01-19 19:18
Agreed.  You can make a notice on activation indication as much to the user.

**Comment by Sinetheta** [comment] 2015-01-19 19:26
I like the idea of a notification, but you really think the default should be "if you install this plugin to a new site it will not work"?

**Comment by infn8** [comment] 2015-01-21 13:56
Very good point.  This is a big issue though because @redpik has a good point.  Perhaps the plugin can do *all* of the following: 

1. Make a notification on activation saying that it's adding them and the default is that those options are set to true (checked).  
* Check if there are styles / scripts already enqueued with the names 'bootstrap-css' and 'bootstrap-js' and if so don't re-register them just enqueue them (so there would only be one copy of each).
* Have a set of filters, eg: ```'bs_shortcodes_add_css'``` that will override the settings in the admin ui 

This way, theme developers have two methods to ensure no collisions occur.  By enqueuing their resources with the same names as the plugin uses, and by filtering them out like:
```php
add_filter("bs_shortcodes_add_css" "__return_false");
add_filter("bs_shortcodes_add_js" "__return_false");
```

**Comment by Sinetheta** [comment] 2015-01-21 18:04
I think the "check if added" is actually something that is okay in our case. Since "bootstrap" is a non-standard lib, there's no way for us to avoid collisions just by enqueuing (since we have no control of what other, if anything, other plugins/themes are enqueuing bootstrap as). What we can do, is modify our lib with a guard, eg: `if($.fn.alert)`.

It's kinda crappy to modify a lib in this way, but WP doesn't give us a lot of options here.

**Comment by thiagof** [comment] 2015-01-30 01:44
I am already happy it can be disabled..

But there are other BS components which deserves place (higher priority, IMHO)

**Comment by Sinetheta** [comment] 2015-08-30 22:53
I'm gonna close this issue as "working as intended", but I would be happy to merge any PRs that improved communication with users, eg: a notification, or explanation after installation.

**Closed by Sinetheta** 2015-08-30 22:53 UTC
